export const data = [
    { id: 1, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 1', passed: true },
    { id: 2, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 2', passed: true },
    { id: 3, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 3' },
    { id: 4, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 4' },
    { id: 5, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 5' },
    { id: 6, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 6' },
    { id: 7, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 7' },
    { id: 8, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 8' },
    { id: 9, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 9' },
    { id: 10, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 10' },
    { id: 11, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 11' },
    { id: 12, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 12' },
    { id: 13, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 13' },
    { id: 14, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 14' },
    { id: 15, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 15' },
    { id: 16, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 16', passed: true },
    { id: 17, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 17', passed: true },
    { id: 18, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 18' },
    { id: 19, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 19' },
    { id: 20, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 20' },
    { id: 21, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 21' },
    { id: 22, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 22' },
    { id: 23, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 23' },
    { id: 24, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 24' },
    { id: 25, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 25' },
    { id: 26, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 26' },
    { id: 27, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 27' },
    { id: 28, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 28' },
    { id: 29, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 29' },
    { id: 30, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 30' },
    { id: 31, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 31' },
    { id: 32, actMess: true, date: '', time: '', date2: '', time2: '', name: 'Авария 32' },
  ];